# Generated by Django 4.2.5 on 2024-01-07 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('username', models.CharField(blank=True, max_length=500, null=True)),
                ('first_name', models.CharField(blank=True, max_length=250, null=True)),
                ('last_name', models.CharField(blank=True, max_length=250, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('country', models.CharField(choices=[('India', 'India')], default='India', max_length=20)),
                ('currency', models.CharField(choices=[('INR', 'INR')], default='INR', max_length=20)),
                ('financial_year', models.CharField(choices=[('1', 'January to December'), ('2', 'April to March')], default='1', max_length=20)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_superadmin', models.BooleanField(default=False)),
                ('profile_photo', models.ImageField(blank=True, max_length=255, null=True, upload_to='photo/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable user account')),
                ('deletion_date', models.DateTimeField(blank=True, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('confirm_password', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AddTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=255)),
                ('segment', models.CharField(max_length=255)),
                ('qty', models.IntegerField()),
                ('trade_type', models.CharField(max_length=255)),
                ('teadeside', models.CharField(choices=[('1', 'Buy'), ('2', 'Sell')], max_length=20)),
                ('entry_price', models.IntegerField()),
                ('entry_date', models.DateTimeField()),
                ('exit_price', models.IntegerField()),
                ('exit_date', models.DateTimeField()),
                ('stop_loss', models.IntegerField(blank=True, null=True)),
                ('take_profit', models.IntegerField(blank=True, null=True)),
                ('brokrage_tax', models.IntegerField()),
                ('profit_n_loss', models.IntegerField()),
                ('chart_img', models.ImageField(blank=True, max_length=255, null=True, upload_to='photo')),
                ('trade_notes', models.TextField()),
                ('gross_profit_loss', models.IntegerField(blank=True, null=True)),
                ('net_profit_loss', models.IntegerField(blank=True, null=True)),
                ('return_percentage', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BrokerageAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=500)),
                ('balance', models.IntegerField()),
                ('total_trade', models.IntegerField()),
                ('win', models.IntegerField()),
                ('loss', models.IntegerField()),
                ('profit_and_loss_amount', models.IntegerField()),
                ('profit_and_loss_percentage', models.IntegerField()),
                ('broker_tax', models.IntegerField()),
                ('account_creation_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'withdrawal')], max_length=20)),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='trade_app.brokerageaccount')),
            ],
        ),
        migrations.CreateModel(
            name='TradeLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=255)),
                ('notes', models.TextField()),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade', to='trade_app.addtrade')),
            ],
        ),
        migrations.AddField(
            model_name='addtrade',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_in_account', to='trade_app.brokerageaccount'),
        ),
    ]
