# Generated by Django 3.1 on 2023-08-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokerageaccount',
            name='account_creation_date',
            field=models.DateTimeField(),
        ),
    ]
