# Generated by Django 3.1 on 2023-08-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_app', '0002_auto_20230822_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtrade',
            name='stop_loss',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addtrade',
            name='take_profit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
